# Generated by Django 4.0.4 on 2022-11-05 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0002_coach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
