# Generated by Django 4.0.4 on 2022-11-05 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0003_alter_coach_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='details',
            field=models.TextField(verbose_name='детальний опис про заняття для групи'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Викладачі, назва групи'),
        ),
    ]
