# Generated by Django 4.0.4 on 2022-11-05 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('digest', '0004_alter_coach_details_alter_coach_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='maintainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Відповідальний за актуальність інформації'),
        ),
    ]
