# Generated by Django 4.0.4 on 2022-11-05 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0005_alter_coach_maintainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='direction',
            field=models.CharField(choices=[('bacha', 'бачата сеншуаль'), ('casno', 'сальса касіно(кубано)'), ('kimba', 'кізомба'), ('urkiz', 'урбанкіз'), ('zouka', 'зук'), ('salna', 'сальса нью-йорк'), ('booga', 'бугі-вугі'), ('menga', 'меренге')], default='menga', max_length=30, verbose_name='напрямок танцю(стиль)'),
        ),
    ]
