# Generated by Django 4.0.4 on 2022-11-10 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('digest', '0007_alter_coach_options_alter_coach_maintainer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brief', models.TextField()),
                ('full', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='coach',
            options={'permissions': (('create_coach', 'create coach'),), 'verbose_name': 'викладач або пара викладачів'},
        ),
        migrations.AlterField(
            model_name='coach',
            name='maintainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Відповідальний за актуальність інформації'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Викладачі, група яку ведуть. наприклад  Юрій Іванов, бачата сеншуаль'),
        ),
    ]
